/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bstree;

import org.junit.Test;
import static org.junit.Assert.*;

public class BSTreeTest {

    @Test public void testOne() {
      BSTree t = new BSTree(0);
      t.insert(1);
      t.insert(-4);
      t.insert(5);
      t.insert(7);
      t.insert(-1);
      t.insert(-9);
      t.insert(-5);
      t.insert(-2);
      t.print();
      for (int i = -9; i < 12; i++){
        System.out.println("Finding " + i + ": " + t.find(i));
      }
    }
}
